x-image-name: &image-name mykytazub/aws-fastapi-project:latest
x-common-env: &common-env
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  CLIENT_ID: ${CLIENT_ID}
  REGION: ${REGION}
  JWT_SECRET: ${JWT_SECRET}
  CLIENT_SECRET: ${CLIENT_SECRET}
  TABLE_NAME: ${TABLE_NAME}

services:
  app:
    image: *image-name
    ports:
      - "127.0.0.1:80:80"
    environment:
      <<: *common-env
    restart: unless-stopped
